# Migration example file.
import_functions:
  pyfile: abs_path_or_relpath_of_script

oracle_configuration:
  username: username_of_db
  password: password_of_db_user
  dsn: tnsname_alias

mongo_server:
  username: mongo_user
  password: mongo_pwd
  host: mongo_host
  db: mongo_db
  auth_source: mongo_auth_source
  port: mongo_port

tables:
  -
    table_name: dbuser.table_name
    query: SELECT COLUMN1, COLUMN2 FROM dbuser.table_name
    collectionName: mongo_target_collection
    columns:
      COLUMN1: column1
      COLUMN2: column2
  -
    table_name: dbuser.table_name2
    query: SELECT COLUMN1, COLUMN2 FROM dbuser.table_name2
    collectionName: mongo_target_collection2
    columns:
      COLUMN1: column1
      COLUMN2: column2 function myscript_function
